# Generated by Django 5.1.3 on 2024-11-21 05:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_todo_delete_post'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='todo',
            name='description',
        ),
    ]
